#!/usr/bin/env bash
set -euo pipefail

echo "=================================================="
echo "❌ [Harness Guard Error]: Test Harness is Empty or Invalid!"
echo "=================================================="
echo "The Sprint test harness script was not properly generated by Refinement."
echo "Halting Sprint loop execution to prevent empty loop running."
echo "Please verify state/initiatives/epic_X/sprint_X_harness.sh and rerun Refinement."
echo "=================================================="
exit 1
